apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  project: default
  source:
    helm: {}
    repoURL: 'https://github.com/vinycloud/descomplicando-gitops-argocd.git'
    targetRevision: feat/argocd
    path: giropops-senhas/helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: giropops-senhas
  syncPolicy:
    automated: 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
